### ISSUE TITLE
Cinema blocks all raw video from playing if CEF fix is not installed despite video's being encoded with VP9

### ISSUE THREAD

**Issue by sappykun** [PurrCoding/cinema#25]
Pretty much what it says on the tin.

In previous versions of Cinema, I noticed that if you played raw videos that were encoded to vp8/9 (the same codec Youtube videos use), then they would actually play properly for people who did not have the CEF codec fix installed. Since that discovery, I have been using vp9 for my video uploads so they can be viewed by both users with the CEF fix and those without it.

Now that there is an in-game check for the codec fix when playing raw video, these videos are being blocked from playing on the client despite being able to play properly otherwise.

Reproduction steps:
1) Factory reset of Gmod (or uninstall CEF codec fix)
2) Join cinema_modded server
3) Queue VP9-encoded video (such as [https://serioussaturdays.net/crash.webm](https://serioussaturdays.net/crash.webm))

Expected result: video plays
Actual result: CEF banner warning pops up, and video does not attempt to play.

**Comment by FarukGamer** [comment]
This is fixed with the latest change https://github.com/PurrCoding/cinema/commit/f9b5ad6919b9d133bd0bfe1c04b4455ff4d58e52, but it will take some time until it is uploaded to the workshop.
