### ISSUE TITLE
[Issue] Ads showing on Youtube

### ISSUE THREAD

**Issue by agentsix1** [PurrCoding/cinema#28]
With the new fix comes new problems. It shows ads which throws off everyone's timing. And if the ads are super long you cant click skip... 

Not  100% certain how to fix that but I hope you can find a way!

**Comment by CattoGamer** [comment]
I won't be able to do anything about it, YouTube is actively working on it so that you can't bypass the ads. The only hope I can give is to rewrite the complete YouTube service and switch to Invidious.

**Comment by agentsix1** [comment]
Interesting. Just being a tiny bit intersted. I did some looking at it. Seems like a cool idea

I was messing with chatgpt to see what it knew about it. It turns out it knows something. I haven't tested any of this code. But if you wanted to mess with it and see what you can manage. Maybe I can put in a few hours tomorrow if you haven't found a fix for it atm.

But this was the script it outputted for me

`
if SERVER then
    util.AddNetworkString("FetchVideoTitle")
    
    -- Function to fetch video title using Invidious API
    function FetchVideoTitle(videoID)
        local url = "https://invidious.snopyta.org/api/v1/videos/" .. videoID
        
        -- Send HTTP request to Invidious API
        http.Fetch(url,
            function(body, len, headers, code)
                if code == 200 then
                    local data = util.JSONToTable(body)
                    if data and data.title then
                        print("Video Title: " .. data.title)
                        
                        -- Sending video title to the client
                        net.Start("FetchVideoTitle")
                        net.WriteString(data.title)
                        net.Broadcast()
                    else
                        print("Error: Unable to fetch video title")
                    end
                else
                    print("Error: HTTP request failed with code " .. code)
                end
            end,
            function(error)
                print("Error: HTTP request failed - " .. error)
            end
        )
    end
    
    -- Example usage
    hook.Add("PlayerSay", "FetchVideoTitleCommand", function(ply, text)
        if string.StartWith(text, "!fetchvideo ") then
            local videoID = string.sub(text, 13)
            FetchVideoTitle(videoID)
            return ""
        end
    end)
end

if CLIENT then
    net.Receive("FetchVideoTitle", function()
        local title = net.ReadString()
        chat.AddText(Color(0, 255, 0), "Video Title: ", Color(255, 255, 255), title)
    end)
end
`

Seems like a fun interesting puzzle to mess with and see what can be learned

**Comment by CattoGamer** [comment]
I'm sorry, but ChatGPT won't really explain to you how to implement anything in such situations. Invidious that many instances that should be as close as possible to the next user.

**Comment by CattoGamer** [comment]
The YouTube service has been rewritten and now runs on other sites, unfortunately this will cause inconvenience for users. Unfortunately there is nothing more I can do.

**Comment by JamTester** [comment]
Have you thought about using invidious or another youtube proxy service?

**Comment by JamTester** [comment]
Is there any reason why Invidious cannot be used?

**Comment by agentsix1** [comment]
> Is there any reason why Invidious cannot be used?

At this time it is being used. It's just not the best method to do it. It does fix the issues I was having. However, sometimes finding an invidious instance that works properly. It's actually kinda annoying but this works and is a better solution than not having it.
