### ISSUE TITLE
[Issue] Direct file media stopped being recognized as valid links

### ISSUE THREAD

**Issue by Vavency** [PurrCoding/cinema#32]
Last known good commit: fba2018
Client broken commit: 01c8347
URL Broken commit: e391711

Sample: https://misskey-taube.s3.eu-central-1.wasabisys.com/files/0024a58c-e6d9-4797-9932-aa7869fd5f7b.webm

**Comment by CattoGamer** [comment]
The problem should be solved with the current changes, please try it out and let me know.

**Comment by Vavency** [comment]
Can't confirm if it works for clients and it doesn't fix other media besides the sample.

More samples:
https://misskey-taube.s3.eu-central-1.wasabisys.com/files/ed30cb21-28bb-4bf6-bed5-0cf1b3ee4d6b.webm
https://misskey-taube.s3.eu-central-1.wasabisys.com/files/1e040f93-8ff1-48c3-9c71-ba87ff38f2a3.webm
https://misskey-taube.s3.eu-central-1.wasabisys.com/files/fe348dde-1e51-4f00-9a2a-13654a56a70c.webm
https://misskey-taube.s3.eu-central-1.wasabisys.com/files/2e2a7fc5-f884-43af-bfde-898a01ba4d7c.webm
https://misskey-taube.s3.eu-central-1.wasabisys.com/files/dfc15183-5056-4a42-96c6-a51d42ef91b4.webm

**Comment by CattoGamer** [comment]
It seems that Git did not take over some changes, this should be fixed now.
